Importing numpy library

In [45]:
import numpy as np

Creating 1D Array

In [46]:
oneD_array = np.array([0,1,2,3,4])
oneD_array.shape

(5,)

Creating 2D Array


In [47]:
twoD_array = np.array([[0,1,2,3,4],[5,6,7,8,9]])
twoD_array.shape

(2, 5)

Creating two 1D Arrays for arithmetic operations


In [ ]:
array1 = np.array([10,6,30])
array2 = np.array([5,2,6])

Addition

In [19]:
#Addition Method-1
array3 = array1+array2
print("Addition Method - 1 : ",array3)


#Addition Method-2
array3 = np.add(array1,array2)
print("Addition Method - 2 : ",array3)

Addition Method - 1 :  [15  8 36]
Addition Method - 2 :  [15  8 36]


Subtraction

In [20]:
#Subtraction Method-1
array3 = array1-array2
print("Subtraction Method - 1 : ",array3)


#Subtraction Method-2
array3 = np.subtract(array1,array2)
print("Subtraction Method - 2 : ",array3)

Subtraction Method - 1 :  [ 5  4 24]
Subtraction Method - 2 :  [ 5  4 24]


Multiplication

In [48]:
#Multiplication Method-1
array3 = array1*array2
print("Multiplication Method - 1 : ",array3)


#Multiplication Method-2
array3 = np.multiply(array1,array2)
print("Multiplication Method - 2 : ",array3)

Multiplication Method - 1 :  [ 50  12 180]
Multiplication Method - 2 :  [ 50  12 180]


Division

In [49]:
#Division Method-1
array3 = array1/array2
print("Division Method - 1 : ",array3)


#Multiplication Method-2
array3 = np.divide(array1,array2)
print("Division Method - 2 : ",array3)

Division Method - 1 :  [2. 3. 5.]
Division Method - 2 :  [2. 3. 5.]


Append

In [26]:
array3 = np.append([0,1,2],[2,3,4])
print("Appended Array : ",array3)

Appended Array :  [0 1 2 2 3 4]


Array Indexing

In [29]:
print("Array Elements of array2 : ",array3)
#From Left to Right
print("1. 5th Element of array3 : ",array3[4])
#From Right to Left
print("2. 5th Element of array3 : ",array3[-2])

Array Elements of array2 :  [0 1 2 2 3 4]
5th Element of array3 :  3
5th Element of array3 :  3


Array Slicing

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
#from left 4
print("1. Sliced Array : ",arr[4:])
#from right 4
print("2. Sliced Array : ",arr[:4])
#from left 1 and right 2
print("3. Sliced Array : ",arr[1:-2])

1. Sliced Array :  [5 6 7]
2. Sliced Array :  [1 2 3 4]
3. Sliced Array :  [2 3 4 5]


Reshaping

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print("New array : ",newarr)
print("Shape of new array : ",newarr.shape)

New array :  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape of new array :  (4, 3)


Array Iteration

In [35]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


Join two arrays

In [36]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


Splitting array

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print("New Array : ",newarr)

New Array :  [array([1, 2]), array([3, 4]), array([5, 6])]


Searching an element in array

In [39]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


Array Sorting

In [41]:
arr = np.array([3, 2, 0, 1])

print("Sorted Array : ",np.sort(arr))

Sorted Array :  [0 1 2 3]


Generation of 1-D Array of random elements

In [42]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[41 93 25 33 84]


Generation of 2-D Array of random elements

In [44]:
from numpy import random

x=random.randint(100, size=(5,2))

print(x)

[[90 97]
 [24 88]
 [34 49]
 [77 17]
 [ 5 43]]
